---
title: "Example_flux_processing"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Example_flux_processing}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(autochamber)
```

Load and visualize data

```{r}
head(data_small_genx)
```

```{r}
head(data_small_chapada)
```

Look at recent raw data

```{r}
recent_raw_genx <- generate_recent_raw(
  data_small_genx,
  today = as_date(max(data_small_genx$TIMESTAMP)))

recent_raw_chapada <- generate_recent_raw(
  data_small_chapada,
  group_col = "location",
  today = as_date(max(data_small_genx$TIMESTAMP)))
```

Visualize

```{r}

```

Calculate fluxes

```{r}
genx_fluxes <- calculate_flux(data_small_genx,
                              cutoff_start = 220,
                              cutoff_end = 510,
                              group_col = NULL)

chapada_fluxes <- calculate_flux(data_small_chapada,
                                 cutoff_start = 180,
                                 cutoff_end = 680,
                                 group_col = "location")
```

Add maintenance log

```{r}
genx_fluxes_cleaned <- 
  add_maintenance_log(slopes = genx_fluxes,
                      gs_url =  "http://docs.google.com/spreadsheets/d/1_uk8-335NDJOdVU6OjLcxWx4MamNJeVEbVkSmdb9oRs/edit?gid=0#gid=0"
  )

chapada_fluxes_cleaned <- 
  add_maintenance_log(slopes = chapada_fluxes,
                      gs_url =  "https://docs.google.com/spreadsheets/d/103PpjEmjLAQkov9ywjA5KxyJiIP3nEWy7V8gWVZhd1M/edit?gid=0#gid=0"
  )
```

Partition

```{r}
partition_co2()
```

Interpolate

```{r}
interpolate()
```

